version: "3.5"
services:
  fit-friends.frontend:
    container_name: fit-friend.frontend
    restart: always
    image: fit-friends.frontend:latest
    env_file:
      - .fit-friends.frontend.env
    ports:
      - "4001:3000"
    networks:
      - fit-friends.frontend.network

networks:
  fit-friends.frontend.network:
    driver: bridge
