version: '3.5'
services:
  fit-friends.bff:
    container_name: fit-friends.bff
    restart: always
    image: fit-friends.bff:latest
    env_file:
      - .fit-friends.bff.env
    ports:
      - '4000:4000'
    networks:
      - fit-friends.bff
      - fit-friends.rabbit

networks:
  fit-friends.bff:
    external: true
  fit-friends.rabbit:
    external: true
