@AToken={{login.response.body.accessToken}}
@RToken={{login.response.body.refreshToken}}

# Регистрация пользователя
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "name": "John Doe",
  "password": "123456",
  "avatar": "avatar1.png",
  "sex": "male",
  "birthDate": "14.10.2023",
  "role": "sportsman",
  "description": "John sportsman description",
  "location": "pionerskaya",
  "photo": "photo1.png",
  "fitnessLevel": "beginner",
  "workoutType": ["yoga"],
  "sportsmanInfo":{
    "workoutTime" :"10-30 мин",
    "caloriesTotal": 1000,
    "caloriesPerDay": 1000,
    "isReady": true
    }
}

###

# Вход в систему
# @name login
POST http://localhost:3001/api/auth/login HTTP/1.1
Authorization: Bearer {{AToken}} {{RToken}}
Content-Type: application/json

# # # Sportsman
{
  "email": "user@test.local",
  "password": "123456"
}

##Coach
# {
#   "email": "first-coach@test.ru",
#   "password": "test123"
# }


###

# Новая JWT пара токенов
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer {{RToken}}

###

# Проверка токена
POST http://localhost:3001/api/auth/check HTTP/1.1
Authorization: Bearer {{AToken}}

###
# Отзыв токена
POST http://localhost:3001/api/auth/revoke HTTP/1.1
Authorization: Bearer {{AToken}}

###
