@fileId={{uploadFile.response.body.id}}

# Upload avatar
# @name uploadFile
POST http://localhost:3002/api/files/upload/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="photo-1@2x.png"
Content-Type: image/png

< ../../../assets/photo-1@2x.png
--boundary--

###

# Upload user photo
# @name uploadFile
POST http://localhost:3002/api/files/upload/user-photo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="user-photo"; filename="user-card-photo1.jpg"
Content-Type: image/jpeg

< ../../../assets/user-card-photo1.jpg
--boundary--

###

# Upload workout photo
# @name uploadFile
POST http://localhost:3002/api/files/upload/workout-photo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="workout-photo"; filename="training-1.png"
Content-Type: image/png

< ../../../assets/training-1.png
--boundary--

###



# Upload certificate
# @name uploadFile
POST http://localhost:3002/api/files/upload/certificate HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="certificate"; filename="1.pdf"
Content-Type: application/pdf

< ../../../assets/1.pdf
--boundary--

###

# Upload video
# @name uploadFile
POST http://localhost:3002/api/files/upload/video HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="video"; filename="1.pdf"
Content-Type: video/mp4

< ../../../assets/Video_HTML_Academy_1.mp4
--boundary--

###

# Get file by ID
GET http://localhost:3002/api/files/{{fileId}} HTTP/1.1

###	###
