@AToken={{login.response.body.accessToken}}
# Login user by email and password
# @name login
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

# Sportsman
{
  "email": "user@test.local",
  "password": "123456"
}

# Coach
# {
#   "email": "first-coach@test.ru",
#   "password": "test123"
# }

###



# Get user  by ID
GET http://localhost:3001/api/user-info/2 HTTP/1.1
Authorization: Bearer {{AToken}}

###


# Get userList
GET http://localhost:3001/api/user-info/show?workoutType=yoga&location=pionerskaya,zvyozdnaya HTTP/1.1
Authorization: Bearer {{AToken}}
# Query params
## role=coach
## workoutType=yoga || workoutType=yoga,stretching
## fitnessLevel=pro
## location=pionerskaya || location=pionerskaya,zvyozdnaya
###

# Update user
PATCH http://localhost:3001/api/user-info/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "description": "Sportsman beginner long description",
  "fitnessLevel": "beginner",
  "workoutType": ["aerobics", "crossfit"]
}

###
